version: '2'
services:
        nginx001:
                image: nginx
                volumes:
                        - ./proxy.conf:/etc/nginx/conf.d/default.conf
                ports:
                        - "8081:80"
                environment:
                        - NGINX_HOST=104.36.67.193
                        - NGINX_PORT=80
                cpu_quota: 2000
                command: /bin/bash -c "nginx -g 'daemon off;'"
                restart: always
