#db实例1
mysql001:
    image: "mysql:latest"
    environment:
        - MYSQL_ROOT_PASSWORD=123
    volumes:
        - /data/docker/mysql001_Data:/var/lib/mysql
    restart: always

#wiki文档系统
devMediawiki:
    image: 'synctree/mediawiki'
    ports:
        - "10080:80"
    links:
        - mysql001:mysql
    volumes:
        - /data/docker/mediawiki:/var/www/html
    restart: always

